add fyi about mismatched config values
expo/fyi pull request #116
Opened 2023-05-25 13:18 UTC by wkozyra95

fyi page that could be linked in error here https://github.com/expo/eas-build/pull/228

2023-05-25 13:42 UTC, szdziedzic approved these changes
Thanks for adding this page!

2023-05-29 21:26 UTC, brentvatne requested changes

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +Part of the build process on EAS Build is evaluation of the content of **app.json/app.config.js** file. In some cases, if the project is misconfigured, resulting config object might have an incorrect
```suggestion
Part of the build process on EAS Build is evaluation of the content of **app.json/app.config.js** file. In some cases, if the project is misconfigured, the resulting config object may contain incorrect values e.g. the build is running under project A, but `extra.projectId` refers to project B.
```

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +When building from EAS CLI we are using both environment variables from your local environment and values from **eas.json**, but on the EAS Build worker only values from **eas.json** (and EAS Secrets
```suggestion
When building from EAS CLI we are using both environment variables from your local environment and values from **eas.json**, but on the EAS Build worker only values from **eas.json** and EAS Secrets will be present. It's common to use dynamic app config (**app.config.js/app.config.ts**) to switch between different configuration based on environment variables. When building on EAS, users need to make sure that environment on the EAS Build will match what was set locally.
```

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +    projectId = '23847707-bf15-424c-b1dc-7a57fc34a23d';
```suggestion
  projectId = '23847707-bf15-424c-b1dc-7a57fc34a23d';
```

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +    projectId = 'db096609-2c67-431d-b83d-88cabf8511b1';
```suggestion
  projectId = 'db096609-2c67-431d-b83d-88cabf8511b1';
```

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +    "build": {
let's use 2 spaces here for indentation for consistency

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +> NOTE: Above advice only applies to the build command and other commands that accept the build profile as a parameter, for other commands you will still need to pass environment variable in the cli
```suggestion
> NOTE: The above advice only applies to the build command and other commands that accept the build profile as a parameter — for other commands that run entirely locally, you will still need to pass environment variable in the cli e.g. `APP=app1 eas update`.
```

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +When running builds from GitHub there is no local environment that might cause inconstancies, but it's still possible that you might connect a repository to the wrong EAS project or misconfigure conn
```suggestion
When running builds from GitHub there is no local environment that might cause inconsistencies, but it's still possible that you might connect a repository to the wrong EAS project or misconfigure a connection to multiple projects.
```

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +If you are connecting single GitHub repository to multiple EAS projects you need to make sure that projectId/slug/owner is matching the correct value for a project that build is executed on.
```suggestion
If you are connecting single GitHub repository to multiple EAS projects you need to make sure that the `projectId`/`slug`/`owner` all match the correct value for a project that build is executed on.
```

2023-05-29 21:26 UTC, brentvatne commented on eas-config-mismatch.md
> +# Evaluating app config on EAS Build workers.
```suggestion
# Evaluating app config on EAS Build workers
```

2023-06-01 09:36 UTC, merged